
- hosts: service_hosts
  vars:
    compose_yaml: /var/tmp/docker-compose.yaml

  remote_user: root
  gather_facts: False
  serial: 1

  pre_tasks:
    - name: "Disable {{ servername }}"
      delegate_to: localhost
      netscaler_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        disabled: yes

        name: "{{ servername }}"

  post_tasks:

    - name: "Re enable {{ servername }}"
      delegate_to: localhost
      netscaler_server:
        nsip: "{{ nsip }}"
        nitro_user: "{{ nitro_user }}"
        nitro_pass: "{{ nitro_pass }}"

        disabled: no
        name: "{{ servername }}"

  tasks:

    - name: "Update backend {{ servername }}"
      command: docker-compose -f "{{ compose_yaml }}" exec -d webserver bash -c "echo 'hello updated {{ servername }}' > /app/content.txt"
